# Generated by Django 4.1.5 on 2023-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
