# Generated by Django 4.1.5 on 2023-05-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
    ]
