# Generated by Django 4.1.5 on 2023-05-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_rename_user_id_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_escription',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='event_status',
        ),
    ]
