# Generated by Django 4.1.5 on 2023-05-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_rename_description_event_event_escription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_escription',
            new_name='event_description',
        ),
    ]
